dist: trusty

language: d

d:
  - dmd
  #- gdc is disabled, waiting for std.experimental.logger
  - ldc

addons:
  apt:
    packages:
      - libevent-pthreads-2.0-5

  postgresql: 9.6

services: postgresql

before_install:
  - dub fetch dscanner

before_script:
  - psql -c 'create database "vibe-test"' -U postgres

script:
  - ./.test.sh "dbname=vibe-test"

after_success:
  - if [ ${DC} = "dmd" ]; then bash <(curl -s https://codecov.io/bash); fi
